name: example_plugin
human_name: Example Plugin
server_link: https://github.com/example/ai-example-plugin
version: 0.1.0
required_backend: '>=0.0.0'
files:
  - actions
  - recommenders
depends_on: []
